language: go

go:
  - 1.7.x

# this is necessary for fork builds to work
go_import_path: github.com/runabove/metronome

before_install:
  - go get github.com/Masterminds/glide

script:
  - glide install
  - make
